name: 'Discord webhooks'
description: 'An action sending Discord build notifications'
inputs:
  version:
    description: 'The build version'
    required: false
    default: '?'
  webhook_url:
    description: 'The Discord webhook URL'
    required: true
  status:
    description: 'The status of the build'
    required: true
  fields:
    description: 'Additional fields in the embed'
    required: false
  include_commit_message:
    required: false
    description: 'If to include the commit message in the embed'
    default: 'true'
  github_token:
    description: 'The GitHub Token'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
